#!/bin/bash
SUFFIX=""
FILE=""

while test $# -gt 0; do
  case "$1" in
    -h|--help)
	  echo "Usage: candle-config [--cflags] [--libs] [--emscripten]"
      exit 0
      ;;
    --emscripten)
      SUFFIX="_emscripten"
	  shift
      ;;
    --debug)
      SUFFIX="_debug"
	  shift
      ;;
    --libs)
	  shift
	  FILE="libs"
      ;;
    --cflags)
	  shift
	  FILE="cflags"
      ;;
    *)
      break;
      ;;
  esac
done

cat candle/build/$FILE$SUFFIX
